config/routes.rb
Rails.application.routes.draw do
  resources :diagnosis_types
  resources :diagnosis_cis
  resources :diagnosis_dementia
  resources :patient_aacc_diseases
  resources :complementary_tests_types
  resources :complementary_tests
  resources :messages
  resources :analytics
  resources :patient_aacc_analytics
  scope :admin do
    resources :professions
      resources :activity_types #FAP o FAE
    resources :habits
    resources :prescription_drugs_types
    resources :exploration_types
    resources :tests
    resources :diagnosis_types
    resources :complementary_tests_types
    resources :diagnosis_types
    resources :diagnosis_cis
    resources :diagnosis_dementia
  end
  resources :patient_aacc_prescriptions
  resources :patient_aacc_tests
  resources :patient_aacc_symptoms
  resources :aaccs
  resources :patient_aacc_habits
  get 'home/index'
  get "admin", to: "admin#index"
  get "admin/physicians", to: "admin#physicians"
  get "admin/new_physician", to: "admin#new_physician"
  get "admin/dis_physician", to: "admin#dis_physician"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  #resources :patients
  root "patients#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :patients do
    resources :aaccs do
      resources :patient_aacc_symptoms#, shallow: true
      resources :patient_aacc_tests, only: [:index, :new] #, shallow: true
      resources :patient_aacc_habits
      resources :patient_aacc_prescriptions
      resources :patient_aacc_diseases
      
      
      get 'patient_aacc_diagnosis/new_computacional_diagnosis1', to: "patient_aacc_diseases#new_computacional_diagnosis1", as: :new_computacional_diagnosis1
      get 'patient_aacc_diagnosis/new_computacional_diagnosis2', to: "patient_aacc_diseases#new_computacional_diagnosis2", as: :new_computacional_diagnosis2

      get 'exploracion_funcional', to: "patient_aacc_symptoms#exploracion_funcional", as: :exploracion_funcional
      get 'exploracion_neurologica', to: "patient_aacc_symptoms#exploracion_neurologica", as: :exploracion_neurologica
      get 'exploracion_fisica', to: "patient_aacc_symptoms#exploracion_fisica", as: :exploracion_fisica
      get 'patient_aacc_tests/new_test_barthel', to: "patient_aacc_tests#new_test_barthel", as: :new_test_barthel
      get 'patient_aacc_tests/new_test_fast', to: "patient_aacc_tests#new_test_fast", as: :new_test_fast
      get 'patient_aacc_tests/new_test_informador', to: "patient_aacc_tests#new_test_informador", as: :new_test_informador
      get 'patient_aacc_tests/new_test_katz', to: "patient_aacc_tests#new_test_katz", as: :new_test_katz
      get 'patient_aacc_tests/new_test_lawton_brody', to: "patient_aacc_tests#new_test_lawton_brody", as: :new_test_lawton_brody
      get 'patient_aacc_tests/new_test_mec', to: "patient_aacc_tests#new_test_mec", as: :new_test_mec
      get 'patient_aacc_tests/new_test_minimental', to: "patient_aacc_tests#new_test_minimental", as: :new_test_minimental
      get 'patient_aacc_tests/new_test_npi', to: "patient_aacc_tests#new_test_npi", as: :new_test_npi
      get 'patient_aacc_tests/new_test_pfeiffer', to: "patient_aacc_tests#new_test_pfeiffer", as: :new_test_pfeiffer
      get 'patient_aacc_tests/new_test_reloj', to: "patient_aacc_tests#new_test_reloj", as: :new_test_reloj
      get 'patient_aacc_tests/new_test_yesavage_4', to: "patient_aacc_tests#new_test_yesavage_4", as: :new_test_yesavage_4
      get 'patient_aacc_tests/new_test_yesavage_10', to: "patient_aacc_tests#new_test_yesavage_10", as: :new_test_yesavage_10
      get 'patient_aacc_tests/new_test_yesavage_15', to: "patient_aacc_tests#new_test_yesavage_15", as: :new_test_yesavage_15
      get 'patient_aacc_tests/new_test_yesavage_30', to: "patient_aacc_tests#new_test_yesavage_30", as: :new_test_yesavage_30
    end
  end
  get "aacc/all_history", to: "aaccs#all_history", as: :all_history
  get "aacc/diagnosis_history", to: "aaccs#diagnosis_history", as: :diagnosis_history
  get "aacc/fe_history", to: "aaccs#fe_history", as: :fe_history
  get "aacc/pc_history", to: "aaccs#pc_history", as: :pc_history
  get "aacc/pf_history", to: "aaccs#pf_history", as: :pf_history
  get "aacc/pi_history", to: "aaccs#pi_history", as: :pi_history
  get "aacc/sc_history", to: "aaccs#sc_history", as: :sc_history
  get "aacc/snc_history", to: "aaccs#snc_history", as: :snc_history
  get "aacc/habits_history", to: "aaccs#habits_history", as: :habits_history
  resources :calculator
  #get 'patients/:patient_id/aaccs/:id/edit', to: 'aaccs#edit'
  get "calculator", to: "calculator#index"


end

app/controllers/prescription_drugs_types_controller.rb
class PrescriptionDrugsTypesController < ApplicationController
  before_action :set_prescription_drugs_type, only: %i[ show edit update destroy ]

  # GET /prescription_drugs_types or /prescription_drugs_types.json
  def index
    @prescription_drugs_types = PrescriptionDrugsType.all
  end

  # GET /prescription_drugs_types/1 or /prescription_drugs_types/1.json
  def show
  end

  # GET /prescription_drugs_types/new
  def new
    @prescription_drugs_type = PrescriptionDrugsType.new
  end

  # GET /prescription_drugs_types/1/edit
  def edit
  end

  # POST /prescription_drugs_types or /prescription_drugs_types.json
  def create
    @prescription_drugs_type = PrescriptionDrugsType.new(prescription_drugs_type_params)

    respond_to do |format|
      if @prescription_drugs_type.save
        format.html { redirect_to @prescription_drugs_type, notice: "Prescription drugs type was successfully created." }
        format.json { render :show, status: :created, location: @prescription_drugs_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prescription_drugs_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescription_drugs_types/1 or /prescription_drugs_types/1.json
  def update
    respond_to do |format|
      if @prescription_drugs_type.update(prescription_drugs_type_params)
        format.html { redirect_to @prescription_drugs_type, notice: "Prescription drugs type was successfully updated." }
        format.json { render :show, status: :ok, location: @prescription_drugs_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prescription_drugs_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescription_drugs_types/1 or /prescription_drugs_types/1.json
  def destroy
    @prescription_drugs_type.destroy
    respond_to do |format|
      format.html { redirect_to prescription_drugs_types_url, notice: "Prescription drugs type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prescription_drugs_type
      @prescription_drugs_type = PrescriptionDrugsType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prescription_drugs_type_params
      params.require(:prescription_drugs_type).permit(:idn, :description, :description_EN)
    end
end

app/helpers/prescription_drugs_types_helper.rb
module PrescriptionDrugsTypesHelper
end

app/views/prescription_drugs_types/_form.html.erb
<%= form_with(model: prescription_drugs_type) do |form| %>
  <% if prescription_drugs_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription_drugs_type.errors.count, "error") %> prohibited this prescription_drugs_type from being saved:</h2>

      <ul>
        <% prescription_drugs_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idn %>
    <%= form.hidden_field :idn %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :description_EN %>
    <%= form.text_field :description_EN %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/prescription_drugs_types/edit.html.erb
<h1>Editing Prescription Drugs Type</h1>

<%= render 'form', prescription_drugs_type: @prescription_drugs_type %>

<%= link_to 'Show', @prescription_drugs_type %> |
<%= link_to 'Back', prescription_drugs_types_path %>

app/views/prescription_drugs_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescription Drugs Types</h1>

<table>
  <thead>
    <tr>
      <th>Idn</th>
      <th>Description</th>
      <th>Description en</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescription_drugs_types.each do |prescription_drugs_type| %>
      <tr>
        <td><%= prescription_drugs_type.idn %></td>
        <td><%= prescription_drugs_type.description %></td>
        <td><%= prescription_drugs_type.description_EN %></td>
        <td><%= link_to 'Show', prescription_drugs_type %></td>
        <td><%= link_to 'Edit', edit_prescription_drugs_type_path(prescription_drugs_type) %></td>
        <td><%= link_to 'Destroy', prescription_drugs_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription Drugs Type', new_prescription_drugs_type_path %>

app/views/prescription_drugs_types/new.html.erb
<h1>New Prescription Drugs Type</h1>

<%= render 'form', prescription_drugs_type: @prescription_drugs_type %>

<%= link_to 'Back', prescription_drugs_types_path %>

app/views/prescription_drugs_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idn:</strong>
  <%= @prescription_drugs_type.idn %>
</p>

<p>
  <strong>Description:</strong>
  <%= @prescription_drugs_type.description %>
</p>

<p>
  <strong>Description en:</strong>
  <%= @prescription_drugs_type.description_EN %>
</p>

<%= link_to 'Edit', edit_prescription_drugs_type_path(@prescription_drugs_type) %> |
<%= link_to 'Back', prescription_drugs_types_path %>