config/routes.rb
Rails.application.routes.draw do
  resources :diagnosis_types
  resources :diagnosis_cis
  resources :diagnosis_dementia
  resources :patient_aacc_diseases
  resources :complementary_tests_types
  resources :complementary_tests
  resources :messages
  resources :analytics
  resources :patient_aacc_analytics
  scope :admin do
    resources :professions
      resources :activity_types #FAP o FAE
    resources :habits
    resources :prescription_drugs_types
    resources :exploration_types
    resources :tests
    resources :diagnosis_types
    resources :complementary_tests_types
    resources :diagnosis_types
    resources :diagnosis_cis
    resources :diagnosis_dementia
  end
  resources :patient_aacc_prescriptions
  resources :patient_aacc_tests
  resources :patient_aacc_symptoms
  resources :aaccs
  resources :patient_aacc_habits
  get 'home/index'
  get "admin", to: "admin#index"
  get "admin/physicians", to: "admin#physicians"
  get "admin/new_physician", to: "admin#new_physician"
  get "admin/dis_physician", to: "admin#dis_physician"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  #resources :patients
  root "patients#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :patients do
    resources :aaccs do
      resources :patient_aacc_symptoms#, shallow: true
      resources :patient_aacc_tests, only: [:index, :new] #, shallow: true
      resources :patient_aacc_habits
      resources :patient_aacc_prescriptions
      resources :patient_aacc_diseases
      
      
      get 'patient_aacc_diagnosis/new_computacional_diagnosis1', to: "patient_aacc_diseases#new_computacional_diagnosis1", as: :new_computacional_diagnosis1
      get 'patient_aacc_diagnosis/new_computacional_diagnosis2', to: "patient_aacc_diseases#new_computacional_diagnosis2", as: :new_computacional_diagnosis2

      get 'exploracion_funcional', to: "patient_aacc_symptoms#exploracion_funcional", as: :exploracion_funcional
      get 'exploracion_neurologica', to: "patient_aacc_symptoms#exploracion_neurologica", as: :exploracion_neurologica
      get 'exploracion_fisica', to: "patient_aacc_symptoms#exploracion_fisica", as: :exploracion_fisica
      get 'patient_aacc_tests/new_test_barthel', to: "patient_aacc_tests#new_test_barthel", as: :new_test_barthel
      get 'patient_aacc_tests/new_test_fast', to: "patient_aacc_tests#new_test_fast", as: :new_test_fast
      get 'patient_aacc_tests/new_test_informador', to: "patient_aacc_tests#new_test_informador", as: :new_test_informador
      get 'patient_aacc_tests/new_test_katz', to: "patient_aacc_tests#new_test_katz", as: :new_test_katz
      get 'patient_aacc_tests/new_test_lawton_brody', to: "patient_aacc_tests#new_test_lawton_brody", as: :new_test_lawton_brody
      get 'patient_aacc_tests/new_test_mec', to: "patient_aacc_tests#new_test_mec", as: :new_test_mec
      get 'patient_aacc_tests/new_test_minimental', to: "patient_aacc_tests#new_test_minimental", as: :new_test_minimental
      get 'patient_aacc_tests/new_test_npi', to: "patient_aacc_tests#new_test_npi", as: :new_test_npi
      get 'patient_aacc_tests/new_test_pfeiffer', to: "patient_aacc_tests#new_test_pfeiffer", as: :new_test_pfeiffer
      get 'patient_aacc_tests/new_test_reloj', to: "patient_aacc_tests#new_test_reloj", as: :new_test_reloj
      get 'patient_aacc_tests/new_test_yesavage_4', to: "patient_aacc_tests#new_test_yesavage_4", as: :new_test_yesavage_4
      get 'patient_aacc_tests/new_test_yesavage_10', to: "patient_aacc_tests#new_test_yesavage_10", as: :new_test_yesavage_10
      get 'patient_aacc_tests/new_test_yesavage_15', to: "patient_aacc_tests#new_test_yesavage_15", as: :new_test_yesavage_15
      get 'patient_aacc_tests/new_test_yesavage_30', to: "patient_aacc_tests#new_test_yesavage_30", as: :new_test_yesavage_30
    end
  end
  get "aacc/all_history", to: "aaccs#all_history", as: :all_history
  get "aacc/diagnosis_history", to: "aaccs#diagnosis_history", as: :diagnosis_history
  get "aacc/fe_history", to: "aaccs#fe_history", as: :fe_history
  get "aacc/pc_history", to: "aaccs#pc_history", as: :pc_history
  get "aacc/pf_history", to: "aaccs#pf_history", as: :pf_history
  get "aacc/pi_history", to: "aaccs#pi_history", as: :pi_history
  get "aacc/sc_history", to: "aaccs#sc_history", as: :sc_history
  get "aacc/snc_history", to: "aaccs#snc_history", as: :snc_history
  get "aacc/habits_history", to: "aaccs#habits_history", as: :habits_history
  resources :calculator
  #get 'patients/:patient_id/aaccs/:id/edit', to: 'aaccs#edit'
  get "calculator", to: "calculator#index"


end

app/views/admin/dis_physician.html.erb
<h1>DESHABILITAR FACULTATIVO</h1>
<hr>
<%= form_with do |form| %>
  <div class="small-container field">
    <%= form.label :user,"Facultativo" %>
    <%= form.select :user,options_from_collection_for_select(User.all, :_id, :email) , {:prompt => 'Selecciona'}  %>
  </div>
  
  <div class="padding">
    <button name="button" type="submit" class="btn btn-primary">Deshabilitar Facultativo </button>
    </div>
<% end %>

app/views/admin/index.html.erb
<h1>ADMIN</h1>
<hr>
  <li class="nav-item">
    <%= link_to 'FACULTATIVOS', admin_physicians_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'HABITOS', habits_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'PROFESIONES', professions_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'TIPOS DE EXPLORACIÓN', exploration_types_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'TIPOS DE FÁRMACOS', prescription_drugs_types_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'TESTS', tests_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'TIPOS DE PRUEBAS COMPLEMENTARIAS', complementary_tests_types_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'DIAGNOSIS CI', diagnosis_cis_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'DIAGNOSIS DEMENTIA', diagnosis_dementia_url %>
  </li>
  <li class="nav-item">
    <%= link_to 'DIAGNOSIS TYPE', diagnosis_types_url %>
  </li>

app/views/admin/new_physician.html.erb
<h1>NUEVO FACULTATIVO</h1>
<hr>
<%= form_with do |form| %>
  <div class="small-container field">
    <%=form.label :name,"Nombre (*)"%>
    <%=form.text_field :name%>
  </div>

  <div class="small-container field">
        <%=form.label :surname,"Apellidos (*)"%>
        <%=form.text_field :surname %>
  </div>  
  
  <div class="small-container field">
        <%=form.label :email,"Email (*)"%>
        <%=form.text_field :email %>
  </div>
  <div class="small-container field">
        <%=form.label :password,"password (*)"%>
        <%=form.password_field :password %>
  </div>
  <div class="small-container field">
        <%=form.label :cpassword,"Confirmar password (*)"%>
        <%=form.password_field :cpassword %>
  </div>
  <div class="field">
    <%= form.label :activity_type,"Tipo de Facultativo (*)"%>
    <%=form.select(:activity_type, options_for_select([['FAP', 'FAP'], ['FAE', 'FAE']]), prompt: "Seleccionar...")%>
  
  </div>
 
  <div class="padding">
    <button name="button" type="submit" class="btn btn-primary">Dar de Alta Facultativo </button>
    </div>
<% end %>

app/views/admin/physicians.html.erb
<h1>ADMIN FACULTATIVOS</h1>
<hr>
  <li class="nav-item">
    <%= link_to 'DAR DE ALTA', admin_new_physician_url%>
  </li>
  <li class="nav-item">
    <%= link_to 'DESHABILITAR FACULTATIVO', admin_dis_physician_url %>
  </li>