config/routes.rb
Rails.application.routes.draw do
  resources :diagnosis_types
  resources :diagnosis_cis
  resources :diagnosis_dementia
  resources :patient_aacc_diseases
  resources :complementary_tests_types
  resources :complementary_tests
  resources :messages
  resources :analytics
  resources :patient_aacc_analytics
  scope :admin do
    resources :professions
      resources :activity_types #FAP o FAE
    resources :habits
    resources :prescription_drugs_types
    resources :exploration_types
    resources :tests
    resources :diagnosis_types
    resources :complementary_tests_types
    resources :diagnosis_types
    resources :diagnosis_cis
    resources :diagnosis_dementia
  end
  resources :patient_aacc_prescriptions
  resources :patient_aacc_tests
  resources :patient_aacc_symptoms
  resources :aaccs
  resources :patient_aacc_habits
  get 'home/index'
  get "admin", to: "admin#index"
  get "admin/physicians", to: "admin#physicians"
  get "admin/new_physician", to: "admin#new_physician"
  get "admin/dis_physician", to: "admin#dis_physician"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  #resources :patients
  root "patients#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :patients do
    resources :aaccs do
      resources :patient_aacc_symptoms#, shallow: true
      resources :patient_aacc_tests, only: [:index, :new] #, shallow: true
      resources :patient_aacc_habits
      resources :patient_aacc_prescriptions
      resources :patient_aacc_diseases
      
      
      get 'patient_aacc_diagnosis/new_computacional_diagnosis1', to: "patient_aacc_diseases#new_computacional_diagnosis1", as: :new_computacional_diagnosis1
      get 'patient_aacc_diagnosis/new_computacional_diagnosis2', to: "patient_aacc_diseases#new_computacional_diagnosis2", as: :new_computacional_diagnosis2

      get 'exploracion_funcional', to: "patient_aacc_symptoms#exploracion_funcional", as: :exploracion_funcional
      get 'exploracion_neurologica', to: "patient_aacc_symptoms#exploracion_neurologica", as: :exploracion_neurologica
      get 'exploracion_fisica', to: "patient_aacc_symptoms#exploracion_fisica", as: :exploracion_fisica
      get 'patient_aacc_tests/new_test_barthel', to: "patient_aacc_tests#new_test_barthel", as: :new_test_barthel
      get 'patient_aacc_tests/new_test_fast', to: "patient_aacc_tests#new_test_fast", as: :new_test_fast
      get 'patient_aacc_tests/new_test_informador', to: "patient_aacc_tests#new_test_informador", as: :new_test_informador
      get 'patient_aacc_tests/new_test_katz', to: "patient_aacc_tests#new_test_katz", as: :new_test_katz
      get 'patient_aacc_tests/new_test_lawton_brody', to: "patient_aacc_tests#new_test_lawton_brody", as: :new_test_lawton_brody
      get 'patient_aacc_tests/new_test_mec', to: "patient_aacc_tests#new_test_mec", as: :new_test_mec
      get 'patient_aacc_tests/new_test_minimental', to: "patient_aacc_tests#new_test_minimental", as: :new_test_minimental
      get 'patient_aacc_tests/new_test_npi', to: "patient_aacc_tests#new_test_npi", as: :new_test_npi
      get 'patient_aacc_tests/new_test_pfeiffer', to: "patient_aacc_tests#new_test_pfeiffer", as: :new_test_pfeiffer
      get 'patient_aacc_tests/new_test_reloj', to: "patient_aacc_tests#new_test_reloj", as: :new_test_reloj
      get 'patient_aacc_tests/new_test_yesavage_4', to: "patient_aacc_tests#new_test_yesavage_4", as: :new_test_yesavage_4
      get 'patient_aacc_tests/new_test_yesavage_10', to: "patient_aacc_tests#new_test_yesavage_10", as: :new_test_yesavage_10
      get 'patient_aacc_tests/new_test_yesavage_15', to: "patient_aacc_tests#new_test_yesavage_15", as: :new_test_yesavage_15
      get 'patient_aacc_tests/new_test_yesavage_30', to: "patient_aacc_tests#new_test_yesavage_30", as: :new_test_yesavage_30
    end
  end
  get "aacc/all_history", to: "aaccs#all_history", as: :all_history
  get "aacc/diagnosis_history", to: "aaccs#diagnosis_history", as: :diagnosis_history
  get "aacc/fe_history", to: "aaccs#fe_history", as: :fe_history
  get "aacc/pc_history", to: "aaccs#pc_history", as: :pc_history
  get "aacc/pf_history", to: "aaccs#pf_history", as: :pf_history
  get "aacc/pi_history", to: "aaccs#pi_history", as: :pi_history
  get "aacc/sc_history", to: "aaccs#sc_history", as: :sc_history
  get "aacc/snc_history", to: "aaccs#snc_history", as: :snc_history
  get "aacc/habits_history", to: "aaccs#habits_history", as: :habits_history
  resources :calculator
  #get 'patients/:patient_id/aaccs/:id/edit', to: 'aaccs#edit'
  get "calculator", to: "calculator#index"


end

app/views/partials/_aacc.html.erb
<div class="margintop">
  <nav class="navbar navbar-light bg-light">
    <div class="container-fluid ">
      <span class="navbar-text">
      <div class="">Paciente: <%= @paciente.surname %> 
         <%= @paciente.name %> -
          Consulta: <%= @aacc.idn %> <p>
          Fecha Consulta: <%= @aacc.created_at %></div>
      </span>
   </div>
  </nav>
</div>

app/views/partials/_login.html.erb
<div class="card center-block padding">
<h4>SESION DE USUARIO</h4>
<%if user_signed_in? %> 
  <div>
    Está Ud. conectad@ como:
    <%=  current_user.email%>

    <%= button_to 'Finalizar sesión', destroy_user_session_path, method: :delete, :class => "btn btn-primary" %> 

  </div>
  <% else %>
  <form class="new_user" id="new_user" action="/users/sign_in" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="t-bh1xSEsP6U7EdGeNWYpPHUL4z65yWVWQzRZhyX-Uhqi9KkkOG3A30CamitmeItwBeK1RSkV1M9BPSak5neEw" />
    <div class="field">
      <label for="user_email">Email</label><br />
      <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]" id="user_email" />
    </div>
    <div class="field">
      <label for="user_password">Password</label><br />
      <input autocomplete="current-password" type="password" name="user[password]" id="user_password" />
    </div>
    <div class="field">
      <input name="user[remember_me]" type="hidden" value="0" /><input type="checkbox" value="1" name="user[remember_me]" id="user_remember_me" />
      <label for="user_remember_me">Remember me</label>
    </div>

    <div class="actions">
      <input type="submit" name="commit" value="Log in" data-disable-with="Log in" />
    </div>
  </form>


  <a href="/users/sign_up">Sign up</a><br />

  <a href="/users/password/new">Forgot your password?</a><br />
  </div>

<%end%>


</div>

app/views/partials/_message.html.erb
<div class="card padding margintop">
        <h4>BUZON DE INTERCONSULTAS</h4>
                <div>
                <p>
                <%=  %> 
                
      <%= image_tag "1904659-entrada.png", class: 'img-responsive icon' %> <%= link_to "Buzón de entrada: 0",messages_url%>
                <p>             
               
      <%= image_tag "1904676-salida", class: 'img-responsive icon' %> <%= link_to "Solicitudes realizadas: 0"%>
                <p>                  
        
      <%= image_tag "1904660-nuevo.png", class: 'img-responsive icon' %> <%= link_to "Crear Solicitud de Interconsulta realizadas",new_message_url%>
      

                </div>
        </div>
</div>

app/views/partials/_nav.html copy.erb
<nav class="nav  padding">
    <li class="nav-item">
    <%= link_to "Inicio", root_path,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "Búsqueda de Pacientes", patients_path,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "Registrar Nuevo Paciente", new_patient_url,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "ADMIN BORRAR!!!", admin_url,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "INICIAR SESION", user_session_url,class:"nav-link"%>

    </li>
    
</nav>

app/views/partials/_nav.html.erb
<nav class="nav  padding">
    <li class="nav-item">
    <%= link_to "Inicio", root_path,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "Búsqueda de Pacientes", patients_path,class:"nav-link"%>

    </li>
    <li class="nav-item">
    <%= link_to "Registrar Nuevo Paciente", new_patient_url,class:"nav-link"%>

    </li>
    
</nav>

app/views/partials/_patient.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <span class="navbar-text">
     <p class="fs-6">
     Paciente: <%= @paciente.surname %>, <%= @paciente.name %> - 
        Numero de Historia Clínica: <%= @paciente.nhc %></p>
    </span>
  </div>
</nav>

app/views/partials/_symptoms.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Idn</th>
      <th>Aacc</th>
      <th>FECHA</th>
      <th>TIPO DE EXPLORACION</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_aacc_symptoms.each do |patient_aacc_symptom| %>
      <tr>
        <td><%= patient_aacc_symptom.idn %></td>
        <td><%= @aacc.idn %></td>
        <td><%= patient_aacc_symptom.created_at %></td>
        <td>Exploracion Funcional</td>
        <td><%= link_to 'Show', patient_aacc_symptom %></td>
        <td><%= link_to 'Edit', edit_patient_aacc_symptom_path(patient_aacc_symptom) %></td>
        <td><%= link_to 'Destroy', patient_aacc_symptom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>