config/routes.rb
Rails.application.routes.draw do
  resources :diagnosis_types
  resources :diagnosis_cis
  resources :diagnosis_dementia
  resources :patient_aacc_diseases
  resources :complementary_tests_types
  resources :complementary_tests
  resources :messages
  resources :analytics
  resources :patient_aacc_analytics
  scope :admin do
    resources :professions
      resources :activity_types #FAP o FAE
    resources :habits
    resources :prescription_drugs_types
    resources :exploration_types
    resources :tests
    resources :diagnosis_types
    resources :complementary_tests_types
    resources :diagnosis_types
    resources :diagnosis_cis
    resources :diagnosis_dementia
  end
  resources :patient_aacc_prescriptions
  resources :patient_aacc_tests
  resources :patient_aacc_symptoms
  resources :aaccs
  resources :patient_aacc_habits
  get 'home/index'
  get "admin", to: "admin#index"
  get "admin/physicians", to: "admin#physicians"
  get "admin/new_physician", to: "admin#new_physician"
  get "admin/dis_physician", to: "admin#dis_physician"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  #resources :patients
  root "patients#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  resources :patients do
    resources :aaccs do
      resources :patient_aacc_symptoms#, shallow: true
      resources :patient_aacc_tests, only: [:index, :new] #, shallow: true
      resources :patient_aacc_habits
      resources :patient_aacc_prescriptions
      resources :patient_aacc_diseases
      
      
      get 'patient_aacc_diagnosis/new_computacional_diagnosis1', to: "patient_aacc_diseases#new_computacional_diagnosis1", as: :new_computacional_diagnosis1
      get 'patient_aacc_diagnosis/new_computacional_diagnosis2', to: "patient_aacc_diseases#new_computacional_diagnosis2", as: :new_computacional_diagnosis2

      get 'exploracion_funcional', to: "patient_aacc_symptoms#exploracion_funcional", as: :exploracion_funcional
      get 'exploracion_neurologica', to: "patient_aacc_symptoms#exploracion_neurologica", as: :exploracion_neurologica
      get 'exploracion_fisica', to: "patient_aacc_symptoms#exploracion_fisica", as: :exploracion_fisica
      get 'patient_aacc_tests/new_test_barthel', to: "patient_aacc_tests#new_test_barthel", as: :new_test_barthel
      get 'patient_aacc_tests/new_test_fast', to: "patient_aacc_tests#new_test_fast", as: :new_test_fast
      get 'patient_aacc_tests/new_test_informador', to: "patient_aacc_tests#new_test_informador", as: :new_test_informador
      get 'patient_aacc_tests/new_test_katz', to: "patient_aacc_tests#new_test_katz", as: :new_test_katz
      get 'patient_aacc_tests/new_test_lawton_brody', to: "patient_aacc_tests#new_test_lawton_brody", as: :new_test_lawton_brody
      get 'patient_aacc_tests/new_test_mec', to: "patient_aacc_tests#new_test_mec", as: :new_test_mec
      get 'patient_aacc_tests/new_test_minimental', to: "patient_aacc_tests#new_test_minimental", as: :new_test_minimental
      get 'patient_aacc_tests/new_test_npi', to: "patient_aacc_tests#new_test_npi", as: :new_test_npi
      get 'patient_aacc_tests/new_test_pfeiffer', to: "patient_aacc_tests#new_test_pfeiffer", as: :new_test_pfeiffer
      get 'patient_aacc_tests/new_test_reloj', to: "patient_aacc_tests#new_test_reloj", as: :new_test_reloj
      get 'patient_aacc_tests/new_test_yesavage_4', to: "patient_aacc_tests#new_test_yesavage_4", as: :new_test_yesavage_4
      get 'patient_aacc_tests/new_test_yesavage_10', to: "patient_aacc_tests#new_test_yesavage_10", as: :new_test_yesavage_10
      get 'patient_aacc_tests/new_test_yesavage_15', to: "patient_aacc_tests#new_test_yesavage_15", as: :new_test_yesavage_15
      get 'patient_aacc_tests/new_test_yesavage_30', to: "patient_aacc_tests#new_test_yesavage_30", as: :new_test_yesavage_30
    end
  end
  get "aacc/all_history", to: "aaccs#all_history", as: :all_history
  get "aacc/diagnosis_history", to: "aaccs#diagnosis_history", as: :diagnosis_history
  get "aacc/fe_history", to: "aaccs#fe_history", as: :fe_history
  get "aacc/pc_history", to: "aaccs#pc_history", as: :pc_history
  get "aacc/pf_history", to: "aaccs#pf_history", as: :pf_history
  get "aacc/pi_history", to: "aaccs#pi_history", as: :pi_history
  get "aacc/sc_history", to: "aaccs#sc_history", as: :sc_history
  get "aacc/snc_history", to: "aaccs#snc_history", as: :snc_history
  get "aacc/habits_history", to: "aaccs#habits_history", as: :habits_history
  resources :calculator
  #get 'patients/:patient_id/aaccs/:id/edit', to: 'aaccs#edit'
  get "calculator", to: "calculator#index"


end

app/models/patient_aacc_habit.rb
class PatientAaccHabit
  include Mongoid::Document
  include Mongoid::Timestamps
  auto_increment :idn
  belongs_to :habit
  field :comments, type: String
  belongs_to :aacc, :class_name => "Aacc", :foreign_key => 'aacc_id', :index => "idn"
  belongs_to :patient
end

app/controllers/patient_aacc_habits_controller.rb
class PatientAaccHabitsController < ApplicationController
  before_action :set_patient_aacc_habit, only: %i[ show edit update destroy ]
  before_action :set_patient, only: %i[ habits_history ]

  # GET /patient_aacc_habits or /patient_aacc_habits.json
  def index
    @patient_aacc_habits = PatientAaccHabit.all
  end

  #def habits_history
  #  @patient_aacc_habits = PatientAaccHabit.where(patient: @paciente)
  #end  
  
  # GET /patient_aacc_habits/1 or /patient_aacc_habits/1.json
  def show
  end

  # GET /patient_aacc_habits/new
  def new
    @patient_aacc_habit = PatientAaccHabit.new
    
  end

  # GET /patient_aacc_habits/1/edit
  def edit
  end

  # POST /patient_aacc_habits or /patient_aacc_habits.json
  def create
    @patient_aacc_habit = PatientAaccHabit.new(patient_aacc_habit_params)
    @patient_aacc_habit.aacc_id = Aacc.last
    @patient_aacc_habit.patient_id = Patient.last
    respond_to do |format|
      if @patient_aacc_habit.save
        format.html { redirect_to @patient_aacc_habit, notice: "Patient aacc habit was successfully created." }
        format.json { render :show, status: :created, location: @patient_aacc_habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_aacc_habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_aacc_habits/1 or /patient_aacc_habits/1.json
  def update
    respond_to do |format|
      if @patient_aacc_habit.update(patient_aacc_habit_params)
        format.html { redirect_to @patient_aacc_habit, notice: "Patient aacc habit was successfully updated." }
        format.json { render :show, status: :ok, location: @patient_aacc_habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_aacc_habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_aacc_habits/1 or /patient_aacc_habits/1.json
  def destroy
    @patient_aacc_habit.destroy
    respond_to do |format|
      format.html { redirect_to patient_aacc_habits_url, notice: "Patient aacc habit was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_aacc_habit
      @patient_aacc_habit = PatientAaccHabit.find(params[:id])
    end    
    def set_patient
      @paciente = Patient.find(params[:patient_id])
    end

    # Only allow a list of trusted parameters through.
    def patient_aacc_habit_params
      params.require(:patient_aacc_habit).permit(:idn, :habit, :comments, :aacc_id, :patient_id)
    end
end

app/helpers/patient_aacc_habits_helper.rb
module PatientAaccHabitsHelper
end

app/views/patient_aacc_habits/_form.html.erb
<%= form_with(model: patient_aacc_habit) do |form| %>
  <% if patient_aacc_habit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient_aacc_habit.errors.count, "error") %> prohibited this patient_aacc_habit from being saved:</h2>

      <ul>
        <% patient_aacc_habit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :idn %>
  </div>

  <div class="field">
    <%= form.hidden_field :aacc_id %>
  </div>

  <div class="field">
    
    <%= form.label :habit,"Hábito (*)"%>
    <%= form.select :habit, options_from_collection_for_select(Habit.all, :_id, :description) , {:prompt => 'Selected Vendor'}  %>
  
  </div>
  
    
  <div class="field">
    <%= form.label :comments,"Comentario" %>
    <%= form.text_area :comments %>
  </div>


  <div class="field">
    <%= form.label :patient_id %>
    <%= form.hidden_field :patient_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patient_aacc_habits/edit.html.erb
<h1>Editing Patient Aacc Habit</h1>

<%= render 'form', patient_aacc_habit: @patient_aacc_habit %>

<%= link_to 'Show', @patient_aacc_habit %> |
<%= link_to 'Back', patient_aacc_habits_path %>

app/views/patient_aacc_habits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histórico de Hábitos del Paciente</h1>
<table>
  <thead>
    <tr>
      <th>NHC PACIENTE</th>
      <th>CONSULTA</th>
      <th>FECHA</th>
      <th>HABITO</th>
      <th>COMENTARIOS</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_aacc_habits.each do |patient_aacc_habit| %>
      <tr>
        <td><%= Patient.find(patient_aacc_habit.patient_id).nhc
        
        
        
        %></td>
        <td><%= patient_aacc_habit.aacc_id %></td>
        <td><%= patient_aacc_habit.created_at %></td>
        <td><%= patient_aacc_habit.habit %></td>
        <td><%= patient_aacc_habit.comments %></td>
        <td><%= link_to 'Show', patient_aacc_habit %></td>
        <td><%= link_to 'Edit', edit_patient_aacc_habit_path(patient_aacc_habit) %></td>
        <td><%= link_to 'Destroy', patient_aacc_habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Idn</th>
      <th>Habit</th>
      <th>Comments</th>
      <th>Aacc</th>
      <th>Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patient_aacc_habits.each do |patient_aacc_habit| %>
      <tr>
        <td><%= patient_aacc_habit.idn %></td>
        <td><%= patient_aacc_habit.habit %></td>
        <td><%= patient_aacc_habit.comments %></td>
        <td><%= patient_aacc_habit.aacc_id %></td>
        <td><%= patient_aacc_habit.patient_id %></td>
        <td><%= link_to 'Show', patient_aacc_habit %></td>
        <td><%= link_to 'Edit', edit_patient_aacc_habit_path(patient_aacc_habit) %></td>
        <td><%= link_to 'Destroy', patient_aacc_habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient Aacc Habit', new_patient_aacc_habit_path %>

app/views/patient_aacc_habits/new.html.erb
<%= link_to '<< Volver a la Exploración Funcional de la Consulta ‘XXX’', patient_aacc_habits_path %>

<h1>Registrar Nuevo Hábito</h1>

<%= render 'form', patient_aacc_habit: @patient_aacc_habit %>

<%= link_to 'Back', patient_aacc_habits_path %>

app/views/patient_aacc_habits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idn:</strong>
  <%= @patient_aacc_habit.idn %>
</p>

<p>
  <strong>Habit:</strong>

        <%= Habit.find(@patient_aacc_habit.habit).description %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @patient_aacc_habit.comments %>
</p>

<p>
  <strong>Aacc:</strong>
  <%= @patient_aacc_habit.aacc_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @patient_aacc_habit.patient_id %>
</p>

<%= link_to 'Edit', edit_patient_aacc_habit_path(@patient_aacc_habit) %> |
<%= link_to 'Back', patient_aacc_habits_path %>